// @ts-check
import eslint from '@eslint/js'
import prettierConfig from 'eslint-config-prettier'
import reactHooks from 'eslint-plugin-react-hooks'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      '.nitro/**',
      '.output/**',
      '.tanstack/**',
      '.netlify/**',
      'src/routeTree.gen.ts',
      'src/components/ui/**', // generated by shadcn
      'scripts/**',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  // ESLint 9+ flat config lives under configs.flat (legacy array form breaks ESLint 10)
  reactHooks.configs.flat['recommended-latest'],
  prettierConfig,
  {
    rules: {
      // interfaces/types often describe payloads not yet referenced everywhere
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
    },
  },
)
